apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rny512wrx-go 
  janus-idp.io/tekton: rny512wrx-go
  backstage.io/kubernetes-id: rny512wrx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rny512wrx-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  