apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rny512wrx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rny512wrx-go 
  name: rny512wrx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rny512wrx-go 
